apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafkacont
spec:
  selector:
    matchLabels:
      app: kafkacont
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kafkacont
    spec:
      containers:
      - image: confluentinc/cp-kafka:7.0.4
        name: kafkacont
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafkacont:29092,PLAINTEXT_HOST://localhost:9092
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: PLAINTEXT
        - name: KAFKA_CREATE_TOPICS
          value: "allocation:1:1"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        # ports:
        # - containerPort: 8761
          # name: kafkacont
---
apiVersion: v1
kind: Service
metadata:
  name: kafkacont
spec:
  type: NodePort
  ports:
  - port: 29092
    nodePort: 30792
    targetPort: 29092
  selector:
    app: kafkacont